name: V3663L.com
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
description: "A website for V3663L: Solo game developer studio developing RPG-and-adjacent games - - - -"
gems:
  - jekyll-seo-tag
